### ISSUE TITLE
parse_varint signed decode error

### ISSUE THREAD

**Issue by jperelli** [astro/rust-protobuf-iter#1]
Hi, see https://github.com/astro/rust-osm-pbf-iter/issues/4 for an explanation. The issue would appear when trying to decode a
`PackedIter<'a, PackedVarint, i32>` or `PackedIter<'a, PackedVarint, i64>`

The issue might be originated somewhere around here https://github.com/astro/rust-protobuf-iter/blob/master/src/parse.rs#L157

I found this npm package that makes a distinction when a signed or unsigned number is trying to be decoded https://github.com/dominictarr/signed-varint/blob/master/index.js#L8
so it seems like that additional math needs to be made when decoding a signed int

**Comment by jperelli** [comment]
I found the actual issue...
there should be somehow an option for i32 without applying zigzag
because protobuf defines actually 3 types
  - uint32: unsigned, without zigzag encoding
  - int32: signed, without zigzag encoding
  - sint32: signed, with zigzag encoding
 and we are missing int32 version

**Comment by astro** [comment]
Turned out this wasn't required for PBF files. Reopen once this becomes a requirement somewhere.
